Soubhagya's Notebook

In [1]:
print("Hello World")

Hello World


Introduction to numpy

In [2]:
import numpy as np

n1=np.array([1,2,3])
print(n1)


[1 2 3]


In [5]:
import numpy as np

n1=np.zeros((4,5))
print(n1)
n2=np.full((5,6),10)
print(n2)
n3=np.arange(5,10,2)
print(n3)
n4=np.random.randint(1,5,10)
print(n4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[5 7 9]
[3 2 4 3 3 1 4 3 1 3]


In [24]:
import numpy as np

n1=np.array([[1,2,3],[3,2,1]])
print(n1.shape)



(2, 3)


In [8]:
import numpy as np

n1=np.array([[1,2,3],[3,2,1]])
n1.shape=(3,2)

print(n1)

[[1 2]
 [3 3]
 [2 1]]


In [17]:
import numpy as np

n1=np.array([1,2,3])
n2=np.array([3,2,7])

print(np.vstack((n1,n2)))
print(np.hstack((n2,n1)))
print(np.column_stack((n1,n2)))
print(np.intersect1d(n1,n2))
print(np.setdiff1d(n2,n1))

[[1 2 3]
 [3 2 7]]
[3 2 7 1 2 3]
[[1 3]
 [2 2]
 [3 7]]
[2 3]
[7]


In [20]:
import numpy as np

n1=np.array([10,20,30])
n2=np.array([5,10,15])

print(np.sum([n1,n2]))
print(np.sum([n1,n2],axis=0))
print(np.sum([n1,n2],axis=1))
n1=n1+5
print("n1=",n1)
n2=n1-4
print(n2)
n2=n2*3
print(n2)
n2=n2/4
print("n2=",n2)

print(np.mean(n2))
print(np.median(n2))
print(np.std(n1))

90
[15 30 45]
[60 30]
n1= [15 25 35]
[11 21 31]
[33 63 93]
n2= [ 8.25 15.75 23.25]
15.75
15.75
8.16496580927726


In [22]:
import numpy as np

n1=np.array([[1,2,3],[2,3,4],[1,2,3]])
n2=np.array([[1,0,0],[1,0,0],[0,0,1]])

print(n1[0])
print(n1[:,2])
print(n1.dot(n2))
print(n1.transpose())
np.save("new_matrix",n1)
n3=np.load("new_matrix.npy")
print(n3)

[1 2 3]
[3 4 3]
[[3 0 3]
 [5 0 4]
 [3 0 3]]
[[1 2 1]
 [2 3 2]
 [3 4 3]]
[[1 2 3]
 [2 3 4]
 [1 2 3]]
